<script type="text/javascript">
var guide = {};
</script>

<table width="100%" style="margin:0;border:0;vertical-align: top;margin-top:50px; height:100%;">
	<tr>
		<td class="main-sidebar">
			<?php if($this->isLogged){
				if($this->watches){ ?>
				<a class="unwatch_button" id="<?php echo $this->series->id?>"><span class="fui-cross" style="padding-right:5px;"></span>Parar de seguir</a>
				<?php } else { ?>
				<a class="watch_button" id="<?php echo $this->series->id?>"><span class="fui-plus" style="padding-right:5px;"></span>Acompanhar Série</a>
				<?php }
			}?>
			<a class="selected"><?php echo $this->series->name?></a>
		</td>
		<td class="sub-sidebar">
			<?php $first = true; $season_num = 0;?>
			<?php foreach ($this->episodes as $episodes) { ?>
				<?php if($episodes->season_id == 0){
					?>
					<script type="text/javascript">
						guide[<?php echo $season_num?>] = {};
						guide[<?php echo $season_num?>][0] = <?php echo json_encode($episodes->jsonObj())?>;
					</script>
					<a <?php if($first){echo 'class="selected"';$first = false;}?> id="s_<?php echo $season_num++?>"><?php echo $episodes->name;?></a>
				<?php }?>
			<?php } ?>
		</td>
		<td class="sub-sub-sidebar">
			<?php $first = true; $season_episodes = array(); $season_num = 0;?>
			<?php foreach ($this->episodes as $episodes) { 
				if($episodes->season_id != 0){ 
					$first = false;
					array_push($season_episodes, $episodes->jsonObj());
				} else if($episodes->season_id == 0 && !$first){
					$json = json_encode($season_episodes);
					$season_episodes = array();
					?>
					<script type="text/javascript">
						guide[<?php echo $season_num++?>][1] = <?php echo $json?>;
					</script>
					<?php 
				}
			}
			$json = json_encode($season_episodes);
			$season_episodes = array();
			?>
			<script type="text/javascript">
				guide[<?php echo $season_num++?>][1] = <?php echo $json?>;
			</script>
		</td>
		<td id="episode-panel">
			<h1><?php echo $this->series->name?></h1>
			<h2></h2>
			<!-- <img class="cover" src="<?php echo HOST?>images/a.jpg" style="margin-right:20px"/>  -->
			<img class="cover" src="<?php echo $this->series->image()?>"/>
			<div id="series-info" >
				<div id="series-data">
					<img src="<?php echo HOST?>images/time.png" width="100px"/>
					<span class="tag">Status:</span><span class="tag-info"><?php echo $this->series->status()?></span>
					<span class="tag">Duração:</span><span class="tag-info"><?php echo $this->series->runtime?> min</span>
					<span class="tag">Data:</span><span class="tag-info airdate"></span>
				</div>
				<?php if($this->isLogged){?>
				<div id="links-data">
					<img src="<?php echo HOST?>images/infinity.png" width="100px"/>
					<span class="tag">Link:</span><a href="" target="_blank" class="tag-info normal"></a>
					<span class="tag">720p:</span><a href="" target="_blank" class="tag-info 720p"></a>
					<span class="tag">1080p:</span><a href="" target="_blank"  class="tag-info 1080p"></a>
				</div>
				<?php }?>
			</div>
		</td>
	</tr>
</table>

<script type="text/javascript">
var current_season;

<?php if($this->isLogged){?>
$(document).on('click','.watch_button',function(e){
	var id = $(this).attr('id');
	$.ajax({
		type : 'POST',
		url  : '<?php echo $this->url(array(),'ajaxWatch',true)?>',
		data : {'id':id},
	});
	$('.main-sidebar').prepend('<a class="unwatch_button" id="'+id+'"><span class="fui-cross" style="padding-right:5px;"></span>Parar de seguir</a>');
	$(this).remove();
});

$(document).on('click','.unwatch_button',function(e){
	var id = $(this).attr('id');
	$.ajax({
		type : 'POST',
		url  : '<?php echo $this->url(array(),'ajaxUnwatch',true)?>',
		data : {'id':id},
	});
	$('.main-sidebar').prepend('<a class="watch_button" id="'+id+'"><span class="fui-plus" style="padding-right:5px;"></span>Acompanhar Série</a>');
	$(this).remove();
});

function loadLinks(selector, value){
	$(selector).empty();
	if(value != ""){
		$(selector).text('Download');
		$(selector).attr('href',value);
	}
}
<?php } ?>

function loadEpisodes(season_num){
	$('.sub-sub-sidebar').empty();
	var length = guide[season_num][1].length;
	for (var i = 0; i < length; i++) {
  		var episode = guide[season_num][1][i];
  		$('.sub-sub-sidebar').append('<a id="e_'+i+'">'+(season_num+1)+'x'+(i+1)+' - '+episode.name+'</a>');
	}
	current_season = season_num;
}

$(document).ready(function(){
	loadEpisodes(0);
	$('#episode-panel h2').append($('.sub-sidebar .selected').text());
});

$('.sub-sidebar a').on('click',function(e){
	$('.sub-sidebar a').removeClass('selected');
	$(this).toggleClass('selected');
	var id  = $(this).attr('id');
	id 		= id.substr(2);
	loadEpisodes(id*1);
	$('#episode-panel h2').empty();
	$('#episode-panel h2').text(guide[current_season][0].name);

	<?php if($this->isLogged){?>
	loadLinks('#links-data .normal',guide[current_season][0].link);
	loadLinks('#links-data .720p'  ,guide[current_season][0].link_720p);
	loadLinks('#links-data .1080p' ,guide[current_season][0].link_1080p);
	<?php }?>
	
	$('#series-data .airdate').text('');
});

$(document).on('click','.sub-sub-sidebar a',function(e){
	$('.sub-sub-sidebar a').removeClass('selected');
	$(this).toggleClass('selected');
	var id  = $(this).attr('id');
	id 		= id.substr(2);
	$('#episode-panel h2').empty();
	$('#episode-panel h2').text(guide[current_season][1][id].name);
	
	<?php if($this->isLogged){?>
	loadLinks('#links-data .normal',guide[current_season][1][id].link);
	loadLinks('#links-data .720p'  ,guide[current_season][1][id].link_720p);
	loadLinks('#links-data .1080p' ,guide[current_season][1][id].link_1080p);
	<?php }?>

	airtime = new Date(guide[current_season][1][id].airdate*1000);
	$('#series-data .airdate').text(airtime.getDate()+'/'+(airtime.getMonth()+1)+'/'+airtime.getFullYear());
});
</script>