		<div id="main">
			<div id="main_left">
				<h1>Acompanhe suas séries</h1>
				<h4>Perdido no meio de tantos seriados? Não consegue lembrar em que episódio parou?</h4>
				<h4>Nós cuidamos disso para você!</h4>
				<img src="/images/main.png" />
			</div>
			<div id="main_right">
				<div class="feature">
					<img src="images/calendar.png" width="75px"/>
					<h4>Veja a data de exibição dos próximos episódios.</h4>
				</div>
				<div class="feature">
					<img src="images/infinity.png" width="75px"/>
					<h4>Sempre atualizado com os mais novos seriados.</h4>
				</div>
				<div class="feature">
					<img src="images/retina.png" width="75px"/>
					<h4>Não se perca. Marque os episódios ja vistos.</h4>
				</div>	
			</div>
		</div>