		<?php $bg_colors = array('#254668','#2b537b','#31608f','#376ca2','#3d79b6'); $color = -1;?>
		<div id="main">
			<?php foreach ($this->series as $series) { 
				++$color;
				if($color>4){ $color = 0; }
				$bg = '';
				if($series->image!='default.png'){
					$bg = ' url(\'../i/'.$series->image.'\') center no-repeat';
				}
				?>
				<div class="series-box" style="background:<?php echo $bg_colors[$color].$bg?> ;">
					<h2><a href="<?php echo $this->url(array('permalink'=>$series->permalink),'seriesDetail',true)?>"><?php echo $series->name;?></a></h2>
				</div>
			<?php }?>
		</div>
		
		<script type="text/javascript">
	    $(document).ready(function(){
	        var page = 2;
	        $(window).scroll(function(){  
	            if($(window).scrollTop() == $(document).height() - $(window).height()){
		            $('#main').append('<img src="<?php echo HOST?>images/ajax-loader.gif" id="gif-loader"/>');
	                $.get('<?php echo $this->url(array(), 'infiniteScroll', true) ?>', {'page':page}, function(data){ $('#main').append(data); $('#gif-loader').remove() } );
	                page++;
	            }  
	        });
	    });
	</script>