		<?php $bg_colors = array('#1abc9c','#16a085','#2ecc71','#27ae60','#3498db','#2980b9','#9b59b6','#8e44ad','#34495e','#2c3e50','#f1c40f','#f39c12','#e67e22','#d35400','#e74c3c','#c0392b','#bdc3c7','#95a5a6','#7f8c8d');?>
		<div id="main">
			<div id="search-title">Busca por <?php echo $this->search?></div>	
			<?php foreach ($this->series as $series) { ?>
				<?php $color = mt_rand(0, 18); ?>
				<div class="series-box" style="background:<?php echo $bg_colors[$color]?> ;">
					<h2><a href="<?php echo $this->url(array('permalink'=>$series->permalink),'seriesDetail',true)?>"><?php echo $series->name;?></a></h2>
				</div>
			<?php }?>
		</div>