		<?php $bg_colors = array('#254668','#2b537b','#31608f','#376ca2','#3d79b6'); $color = -1;?>
		<div id="main">
			<div id="search-title">Busca por <?php echo $this->search?></div>	
			<?php foreach ($this->series as $series) {
				++$color;
				if($color>4){ $color = 0; }?>
				<div class="series-box" style="background:<?php echo $bg_colors[$color]?> ;">
					<h2><a href="<?php echo $this->url(array('permalink'=>$series->permalink),'seriesDetail',true)?>"><?php echo $series->name;?></a></h2>
				</div>
			<?php }?>
		</div>	